// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHFGxfq1eS89gjixncMHgzhQc3LB-ck4',
    appId: '1:6551562988:web:16cc2a8194015cf2cc13c9',
    messagingSenderId: '6551562988',
    projectId: 'expensify-3fd31',
    authDomain: 'expensify-3fd31.firebaseapp.com',
    storageBucket: 'expensify-3fd31.appspot.com',
    measurementId: 'G-N13F1CVZV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGk_mToJ4oMh_4hiTkowaDt5wxI-YfQ4g',
    appId: '1:6551562988:android:be6dceb45ad12f23cc13c9',
    messagingSenderId: '6551562988',
    projectId: 'expensify-3fd31',
    storageBucket: 'expensify-3fd31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3hTk3uMWCdKNY6HwTUljMsF-uBDGX4E',
    appId: '1:6551562988:ios:e315f1e56e3641d7cc13c9',
    messagingSenderId: '6551562988',
    projectId: 'expensify-3fd31',
    storageBucket: 'expensify-3fd31.appspot.com',
    iosClientId:
        '6551562988-ekt0jom96p9hci29l3erd6mu5oplbr0p.apps.googleusercontent.com',
    iosBundleId: 'com.capstone.expensify',
  );
}
